/**
 * Magnet poles.
 *
 * A row of bar magnets on a rail. Tap one to flip it end for end. Every neighbouring pair either pulls
 * together or shoves apart, and the goal states which pattern the rail has to end up in.
 *
 * The rail shows attraction and repulsion live between each pair, so the rule (opposites attract) is
 * discoverable by fiddling rather than stated. Solvability is guaranteed structurally: the target is
 * generated by flipping a real arrangement, never asserted.
 */

import { PAL } from '../../content/brand';
import { drawText, drawTextCentered, wrapText } from '../../core/font';
import type { Input } from '../../core/input';
import type { Rng } from '../../core/rng';
import { play } from '../../core/audio';
import { hit, type Rect } from '../ui/widgets';
import { drawArtFit, hasArt } from '../../core/assets';
import type { Generator, Outcome, Puzzle } from './types';

/** true = North faces right. */
type Magnet = boolean;

/** Adjacent magnets attract when the facing poles differ, i.e. when orientations match. */
function attracts(a: Magnet, b: Magnet): boolean {
  return a === b;
}

type Goal = 'allAttract' | 'allRepel' | 'pattern';

interface Spec {
  goal: Goal;
  /** For 'pattern': the required attract/repel state of each gap. */
  gaps?: boolean[];
  /** Magnets the player can't flip — glued down. */
  locked: boolean[];
}

class MagnetPuzzle implements Puzzle {
  readonly domain = 'magnets' as const;
  readonly prompt: string;
  readonly teach =
    'A magnet has two ends. Two ends that are different pull together; two ends that are the same push apart.';
  readonly hint =
    'Look at the two ends facing each other across a gap, not at the whole magnet. N facing S pulls; N facing N pushes.';
  attempts = 0;

  private state: Outcome = 'open';

  constructor(
    readonly instance: string,
    private readonly mags: Magnet[],
    private readonly spec: Spec,
  ) {
    this.prompt =
      spec.goal === 'allAttract' ? 'Flip magnets until every pair pulls together.'
      : spec.goal === 'allRepel' ? 'Flip magnets until every pair pushes apart.'
      : 'Match the pull/push pattern marked under each gap.';
  }

  private gapState(): boolean[] {
    return this.mags.slice(0, -1).map((m, i) => attracts(m, this.mags[i + 1] as Magnet));
  }

  private want(): boolean[] {
    if (this.spec.goal === 'allAttract') return this.mags.slice(0, -1).map(() => true);
    if (this.spec.goal === 'allRepel') return this.mags.slice(0, -1).map(() => false);
    return this.spec.gaps as boolean[];
  }

  step(input: Input, _dt: number, area: Rect): void {
    if (this.state !== 'open' || !input.pointer.released) return;
    const L = this.layout(area);
    for (let i = 0; i < this.mags.length; i++) {
      if (hit(this.magRect(L, i), input.pointer.x, input.pointer.y)) {
        if (this.spec.locked[i]) {
          play('nope');
          return;
        }
        this.mags[i] = !this.mags[i];
        play('click');
        return;
      }
    }
  }

  check(): void {
    if (this.state !== 'open') return;
    this.attempts++;
    const got = this.gapState();
    const want = this.want();
    const ok = got.every((g, i) => g === want[i]);
    this.state = ok ? 'solved' : 'failed';
    play(ok ? 'ok' : 'nope');
  }

  canCheck(): boolean {
    return true;
  }

  outcome(): Outcome {
    return this.state;
  }

  private layout(area: Rect) {
    const n = this.mags.length;
    const gap = 22;
    const mw = Math.min(86, Math.floor((area.w - 20 - gap * (n - 1)) / n));
    const totalW = n * mw + (n - 1) * gap;
    const x0 = area.x + Math.round((area.w - totalW) / 2);
    const y = area.y + Math.round(area.h * 0.34);
    return { n, mw, gap, x0, y };
  }

  private magRect(L: ReturnType<typeof this.layout>, i: number): Rect {
    return { x: L.x0 + i * (L.mw + L.gap), y: L.y, w: L.mw, h: 28 };
  }

  draw(ctx: CanvasRenderingContext2D, area: Rect, input: Input): void {
    const L = this.layout(area);
    const got = this.gapState();
    const want = this.want();

    // Rail
    ctx.fillStyle = PAL.steel1;
    ctx.fillRect(L.x0 - 10, L.y + 32, L.n * (L.mw + L.gap) - L.gap + 20, 3);

    for (let i = 0; i < L.n; i++) {
      const r = this.magRect(L, i);
      const north = this.mags[i] as boolean;
      const locked = this.spec.locked[i];
      const over = !locked && this.state === 'open' && hit(r, input.pointer.x, input.pointer.y);

      const half = Math.floor(r.w / 2);
      const leftIsN = !north;

      if (hasArt('mag_bar')) {
        // The art is drawn N-left; flipping the sprite is what "turning the magnet around" means.
        ctx.save();
        ctx.translate(r.x + r.w / 2, r.y + r.h / 2);
        if (!leftIsN) ctx.scale(-1, 1);
        if (locked) ctx.globalAlpha = 0.75;
        drawArtFit(ctx, 'mag_bar', 0, 0, r.w, r.h);
        ctx.restore();
        ctx.globalAlpha = 1;
        if (over) {
          ctx.fillStyle = PAL.white;
          ctx.fillRect(r.x - 2, r.y - 2, r.w + 4, 1);
          ctx.fillRect(r.x - 2, r.y + r.h + 1, r.w + 4, 1);
        }
      } else {
        // Two halves, coloured by pole. Letters too — colour alone would fail anyone colourblind.
        ctx.fillStyle = leftIsN ? PAL.rust : PAL.spark;
        ctx.fillRect(r.x, r.y, half, r.h);
        ctx.fillStyle = leftIsN ? PAL.spark : PAL.rust;
        ctx.fillRect(r.x + half, r.y, r.w - half, r.h);
        ctx.fillStyle = over ? PAL.white : locked ? PAL.steel2 : PAL.bone;
        ctx.fillRect(r.x, r.y, r.w, 1);
        ctx.fillRect(r.x, r.y + r.h - 1, r.w, 1);
        ctx.fillRect(r.x, r.y, 1, r.h);
        ctx.fillRect(r.x + r.w - 1, r.y, 1, r.h);
        drawTextCentered(ctx, leftIsN ? 'N' : 'S', r.x + half / 2, r.y + r.h / 2 - 3, PAL.white);
        drawTextCentered(ctx, leftIsN ? 'S' : 'N', r.x + half + (r.w - half) / 2, r.y + r.h / 2 - 3, PAL.white);
      }
      // Above the magnet: below, it landed on the PULL/PUSH target labels.
      if (locked) drawTextCentered(ctx, 'GLUED', r.x + r.w / 2, r.y - 11, PAL.steel2);
    }

    // Between each pair: what it's doing now, and what it needs to do.
    for (let i = 0; i < L.n - 1; i++) {
      const cx = L.x0 + i * (L.mw + L.gap) + L.mw + L.gap / 2;
      const ok = got[i] === want[i];
      const cy = L.y + L.mw * 0.0 + 14;
      ctx.fillStyle = ok ? PAL.volt : PAL.hot;
      if (got[i]) {
        // pulling together
        ctx.fillRect(cx - 4, cy, 3, 1);
        ctx.fillRect(cx + 2, cy, 3, 1);
        ctx.fillRect(cx - 2, cy - 1, 1, 3);
        ctx.fillRect(cx + 2, cy - 1, 1, 3);
      } else {
        // pushing apart
        ctx.fillRect(cx - 5, cy, 3, 1);
        ctx.fillRect(cx + 3, cy, 3, 1);
        ctx.fillRect(cx - 5, cy - 1, 1, 3);
        ctx.fillRect(cx + 5, cy - 1, 1, 3);
      }
      if (this.spec.goal === 'pattern') {
        drawTextCentered(ctx, want[i] ? 'PULL' : 'PUSH', cx, L.y + 40, ok ? PAL.volt : PAL.steel2);
      }
    }

    const done = got.every((g, i) => g === want[i]);
    drawTextCentered(
      ctx,
      done ? 'ALL CORRECT' : `${got.filter((g, i) => g === want[i]).length} OF ${got.length} GAPS RIGHT`,
      area.x + area.w / 2, area.y + 2, done ? PAL.volt : PAL.steel3,
    );

    for (const [i, l] of wrapText('Tap a magnet to turn it around.', area.w - 8).entries()) {
      drawText(ctx, l, area.x + 4, area.y + area.h - 14 + i * 9, PAL.steel2);
    }
  }
}

export const magnetsGen: Generator = {
  domain: 'magnets',
  make(rng: Rng, tier: number): Puzzle {
    const n = tier < 2 ? 3 : tier < 5 ? 4 : 5;

    // Build a solved arrangement first, then scramble the free magnets. Guarantees solvability, and
    // guarantees the locked ones are consistent with a real answer rather than a coincidence.
    const goal: Goal = tier < 2 ? 'allAttract' : rng.pick(['allAttract', 'allRepel', 'pattern'] as Goal[]);
    const solution: Magnet[] = [rng.next() < 0.5];
    const gaps: boolean[] = [];
    for (let i = 1; i < n; i++) {
      const wantAttract =
        goal === 'allAttract' ? true : goal === 'allRepel' ? false : rng.next() < 0.5;
      gaps.push(wantAttract);
      // attracts(a,b) is a === b, so this is forced.
      solution.push(wantAttract ? (solution[i - 1] as boolean) : !(solution[i - 1] as boolean));
    }

    const lockCount = tier < 3 ? 1 : Math.min(n - 2, 1 + Math.floor(tier / 3));
    const lockedIdx = new Set(rng.sample([...Array(n).keys()], lockCount));
    const locked = [...Array(n).keys()].map((i) => lockedIdx.has(i));

    const mags = solution.slice();
    // Scramble the free ones, and make sure we don't hand over an already-solved board.
    for (let tries = 0; tries < 30; tries++) {
      for (let i = 0; i < n; i++) if (!locked[i] && rng.next() < 0.6) mags[i] = !mags[i];
      const solved = mags.every((m, i) => m === solution[i]) ||
        mags.slice(0, -1).every((m, i) => attracts(m, mags[i + 1] as Magnet) === gaps[i]);
      if (!solved) break;
      // Force at least one flip on a free magnet.
      const free = [...Array(n).keys()].filter((i) => !locked[i]);
      if (free.length) mags[rng.pick(free)] = !mags[rng.pick(free)];
    }

    const spec: Spec = goal === 'pattern' ? { goal, gaps, locked } : { goal, locked };
    return new MagnetPuzzle(
      `mag-${goal}-${mags.map((m) => (m ? 'n' : 's')).join('')}-${locked.map((l) => (l ? 'L' : '.')).join('')}`,
      mags, spec,
    );
  },
};

export { MagnetPuzzle };
